services:
  mysql:
    image: mysql:lts
    restart: no
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

# use the following commands to connect to the DB
# docker exec -it mysql bash -l
# mysql -u(username) -p(password)